version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=./database.sqlite
    volumes:
      - ./apps/server/database.sqlite:/app/server/database.sqlite
      - ./apps/server/config:/app/server/config
    restart: unless-stopped

  # Optional: separate database service if using PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: highlite
  #     POSTGRES_USER: highlite
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
