version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./apps/server:/app/server
      - database_data:/app/server
    restart: unless-stopped

  # Optional: separate database service if using PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: highlite
  #     POSTGRES_USER: highlite
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:

volumes:
  database_data:
